# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PermissionGuardian < Formula
  desc "TUI dashboard for managing Claude Code and Codex permission prompts in tmux"
  homepage "https://github.com/buddyh/permission-guardian"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buddyh/permission-guardian/releases/download/v0.1.1/permission-guardian_0.1.1_darwin_amd64.tar.gz"
      sha256 "104702c877001cee263c1ce875893ccfcf5f8df891b22cb824b6f09763fe6e44"

      define_method(:install) do
        bin.install "pg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buddyh/permission-guardian/releases/download/v0.1.1/permission-guardian_0.1.1_darwin_arm64.tar.gz"
      sha256 "e18c4326a75380544796aae0a59c4d15a0c384a99a3664b6a19f62205f0dcd3b"

      define_method(:install) do
        bin.install "pg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buddyh/permission-guardian/releases/download/v0.1.1/permission-guardian_0.1.1_linux_amd64.tar.gz"
      sha256 "aaca7709f889eff08ce128b9838f6efdecc2beba0668ed61ac779f1b8a56a469"
      define_method(:install) do
        bin.install "pg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buddyh/permission-guardian/releases/download/v0.1.1/permission-guardian_0.1.1_linux_arm64.tar.gz"
      sha256 "498adefae73d9b1ff966442b947eda35ac105279a1dbebe3dae81075adea5492"
      define_method(:install) do
        bin.install "pg"
      end
    end
  end

  test do
    system "#{bin}/pg", "--version"
  end
end
