# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todoist < Formula
  desc "Todoist CLI - manage tasks from the command line"
  homepage "https://github.com/buddyh/todoist-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.3.0/todoist_0.3.0_darwin_amd64.tar.gz"
      sha256 "33f7b6b99d001519b5c75e5d9186b4df1fa586becf38219089f0167791f52465"

      def install
        bin.install "todoist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.3.0/todoist_0.3.0_darwin_arm64.tar.gz"
      sha256 "1994cbe639939e1d0cbb60514b9478a0b4bfe4664cda3a71a66e2db25a857d96"

      def install
        bin.install "todoist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.3.0/todoist_0.3.0_linux_amd64.tar.gz"
      sha256 "52f3ffbdefa74287f675894bd244897c21732d3aaf7877b3f7907338d79e74db"
      def install
        bin.install "todoist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.3.0/todoist_0.3.0_linux_arm64.tar.gz"
      sha256 "91c00b567b946e3f51b033eeffa0871bffa9427d9db1d02563300a8fbbb72512"
      def install
        bin.install "todoist"
      end
    end
  end

  test do
    system "#{bin}/todoist", "--version"
  end
end
