# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todoist < Formula
  desc "Todoist CLI - manage tasks from the command line"
  homepage "https://github.com/buddyh/todoist-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.4.0/todoist_0.4.0_darwin_amd64.tar.gz"
      sha256 "835b07af8d345950759f61360e9c9831f3f76dcda5a35864cd3b05803c8fdd47"

      def install
        bin.install "todoist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.4.0/todoist_0.4.0_darwin_arm64.tar.gz"
      sha256 "9b81c5923caee8d1428b0222b46ed63a7feb18d2815477114bfda1b7c02610fe"

      def install
        bin.install "todoist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.4.0/todoist_0.4.0_linux_amd64.tar.gz"
      sha256 "fc21b57f3eefd6b7d33989d7e6df1c232350d5ccbb47e45855dc188d9be7031e"
      def install
        bin.install "todoist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buddyh/todoist-cli/releases/download/v0.4.0/todoist_0.4.0_linux_arm64.tar.gz"
      sha256 "c268daf90b1ca865939210648d437d65fae684b8e442b07ef19cf89dddd0c909"
      def install
        bin.install "todoist"
      end
    end
  end

  test do
    system "#{bin}/todoist", "--version"
  end
end
